package jonk;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Represents one message and an avatar identifying its speaker.
 */
public class DialogBox extends HBox {
    private static final String JONK_AVATAR = "🤖";
    private static final String USER_AVATAR = "🙂";
    private static final String JONK_AVATAR_STYLE =
            "-fx-background-color: #d7f4e3; -fx-background-radius: 28; -fx-font-size: 26;";
    private static final String USER_AVATAR_STYLE =
            "-fx-background-color: #dbeafe; -fx-background-radius: 28; -fx-font-size: 26;";

    @FXML
    private Label dialog;

    @FXML
    private Label avatar;

    private DialogBox(String text, String avatarText, String avatarStyle) {
        FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);

        try {
            fxmlLoader.load();
        } catch (IOException e) {
            throw new AssertionError("DialogBox.fxml could not be loaded", e);
        }

        dialog.setText(text);
        avatar.setText(avatarText);
        avatar.setStyle(avatarStyle);
    }

    /**
     * Creates a right-aligned dialog for a command entered by the user.
     *
     * @param text Command entered by the user.
     * @return User dialog box.
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, USER_AVATAR, USER_AVATAR_STYLE);
    }

    /**
     * Creates a left-aligned dialog for a response generated by Jonk.
     *
     * @param text Response generated by Jonk.
     * @return Jonk dialog box.
     */
    public static DialogBox getJonkDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, JONK_AVATAR, JONK_AVATAR_STYLE);
        dialogBox.flip();
        return dialogBox;
    }

    /**
     * Places the avatar before the message and aligns the dialog to the left.
     */
    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(getChildren());
        Collections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_LEFT);
    }
}
