package jonk;

import java.util.List;
import java.util.Scanner;

/**
 * Handles all interactions between Jonk and the user.
 */
public class Ui {
    private static final String SEPARATOR =
            "____________________________________________________________";
    private static final String BANNER = """
             _  ___  _   _ _  __
                | |/ _ \\| \\ | | |/ /
             _  | | | | |  \\| | ' /\s
            | |_| | |_| | |\\  | . \\\s
             \\___/ \\___/|_| \\_|_|\\_\\""";

    private final Scanner scanner;

    /**
     * Creates a user interface that reads from standard input.
     */
    public Ui() {
        scanner = new Scanner(System.in);
    }

    /**
     * Displays Jonk's banner and greeting.
     */
    public void showWelcome() {
        System.out.println("\t" + SEPARATOR + "\n\t" + BANNER + "\n\t" + formatGreeting()
                + "\n\t" + SEPARATOR);
    }

    /**
     * Formats Jonk's greeting for display in any user interface.
     *
     * @return Jonk's greeting.
     */
    public String formatGreeting() {
        return "Hello! I'm Jonk.\nWhat can I do for you?\nType help to see the available commands.";
    }

    /**
     * Formats the command reference shared by the command-line and graphical interfaces.
     *
     * @return Help page with command syntax, examples, and input conventions.
     */
    public String formatHelp() {
        return """
                Here's what you can do with Jonk:
                help - Show this help page.
                list - Show all tasks and their task numbers.
                todo DESCRIPTION - Add a task without a date.
                  Example: todo read book
                deadline DESCRIPTION /by DATE - Add a task with a due date.
                  Example: deadline return book /by 2026-09-15
                event DESCRIPTION /from DATE /to DATE - Add an event with start and end dates.
                  Example: event project meeting /from 2026-09-16 /to 2026-09-17
                mark NUMBER - Mark a task as done. Example: mark 1
                unmark NUMBER - Mark a task as not done. Example: unmark 1
                delete NUMBER - Delete a task. Example: delete 1
                find KEYWORD - Find tasks containing the keyword. Example: find book
                bye - Exit Jonk.

                Replace uppercase placeholders with your own values; do not type the placeholders.
                Dates use yyyy-MM-dd, for example 2026-09-15.
                Use task numbers from list, starting at 1, for mark, unmark, and delete.
                Find matches are case-sensitive; their displayed numbers are not task numbers from list.
                Descriptions and keywords may contain spaces and must not be empty.
                Command words are lowercase. Type help, list, and bye without arguments.
                Help does not change your tasks.""";
    }

    /**
     * Displays a response generated by Jonk.
     *
     * @param response Response to display.
     */
    public void showResponse(String response) {
        System.out.println(response);
    }

    /**
     * Reads the user's next complete command.
     *
     * @return Command entered by the user.
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /**
     * Displays a separator between command responses.
     */
    public void showSeparator() {
        System.out.println("\t" + SEPARATOR);
    }

    /**
     * Formats every task with its one-based task number.
     *
     * @param tasks Tasks to display.
     * @return Numbered task list.
     */
    public String formatTaskList(List<Task> tasks) {
        return formatNumberedTasks("Here are the tasks in your list:", tasks);
    }

    /**
     * Formats tasks that match a find command.
     *
     * @param matchingTasks Tasks whose descriptions contain the search keyword.
     * @return Numbered matching-task list.
     */
    public String formatMatchingTasks(List<Task> matchingTasks) {
        return formatNumberedTasks("Here are the matching tasks in your list:", matchingTasks);
    }

    /**
     * Formats the supplied tasks with one-based numbers.
     *
     * @param heading Heading to place above the numbered tasks.
     * @param tasks Tasks to display.
     * @return Heading followed by the numbered tasks.
     */
    private String formatNumberedTasks(String heading, List<Task> tasks) {
        StringBuilder response = new StringBuilder(heading);
        for (int i = 0; i < tasks.size(); i++) {
            response.append("\n\t").append(i + 1).append(".").append(tasks.get(i));
        }
        return response.toString();
    }

    /**
     * Formats confirmation that a task's completion status changed.
     *
     * @param task Task whose status changed.
     * @param isDone Whether the task is now complete.
     * @return Task-status confirmation.
     */
    public String formatTaskStatusUpdated(Task task, boolean isDone) {
        String heading;
        if (isDone) {
            heading = "Nice! I've marked this task as done:";
        } else {
            heading = "OK, I've marked this task as not done yet:";
        }
        return heading + "\n\t" + task;
    }

    /**
     * Formats confirmation that a task was added.
     *
     * @param task Added task.
     * @param taskCount Number of tasks after the addition.
     * @return Task-added confirmation.
     */
    public String formatTaskAdded(Task task, int taskCount) {
        return "Got it. I've added this task:\n\t" + task
                + "\nNow you have " + taskCount + " tasks in the list.";
    }

    /**
     * Formats confirmation that a task was deleted.
     *
     * @param task Deleted task.
     * @param taskCount Number of tasks after the deletion.
     * @return Task-deleted confirmation.
     */
    public String formatTaskDeleted(Task task, int taskCount) {
        return "Noted. I've removed this task:\n\t" + task
                + "\nNow you have " + taskCount + " tasks in the list.";
    }

    /**
     * Displays a user-friendly error message.
     *
     * @param message Error message to display.
     */
    public void showError(String message) {
        System.out.println(message);
    }

    /**
     * Displays Jonk's farewell message.
     */
    public void showGoodbye() {
        System.out.println("\t" + SEPARATOR + "\n\t" + formatFarewell() + "\n\t" + SEPARATOR);
    }

    /**
     * Formats Jonk's farewell for display in any user interface.
     *
     * @return Jonk's farewell.
     */
    public String formatFarewell() {
        return "Bye. Hope to see you again soon!";
    }
}
